[project]
name = "learning-python"
version = "0.1.0"
description = "Project Pembelajaran Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
